"""campaigns full schema

Revision ID: 1e1fca8dac4e
Revises: c4c5a176fca8
Create Date: 2026-07-15 11:06:27.738463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1fca8dac4e'
down_revision: Union[str, None] = 'c4c5a176fca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('activity_type', sa.Enum('sorteo', 'incentivo_fuerza_venta', 'compras_consumidor', 'rotacion', name='activity_type'), nullable=True))
    op.add_column('campaigns', sa.Column('objective_type', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('objective_value', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('campaigns', sa.Column('budget', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('campaigns', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('campaigns', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('campaigns', sa.Column('raffle_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('participation_method', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('terms_text', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('qr_url', sa.Text(), nullable=True))
    op.alter_column('campaigns', 'qr_slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'qr_slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('campaigns', 'qr_url')
    op.drop_column('campaigns', 'terms_text')
    op.drop_column('campaigns', 'participation_method')
    op.drop_column('campaigns', 'raffle_at')
    op.drop_column('campaigns', 'end_time')
    op.drop_column('campaigns', 'start_time')
    op.drop_column('campaigns', 'brand')
    op.drop_column('campaigns', 'category')
    op.drop_column('campaigns', 'budget')
    op.drop_column('campaigns', 'objective_value')
    op.drop_column('campaigns', 'objective_type')
    op.drop_column('campaigns', 'activity_type')
    # ### end Alembic commands ###
