"""cufe integration

Revision ID: 8efb606e846b
Revises: 1e1fca8dac4e
Create Date: 2026-07-15 19:25:02.049774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efb606e846b'
down_revision: Union[str, None] = '1e1fca8dac4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'participant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'participant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
